language: ruby
sudo: false
rvm:
  - "2.0.0"
  - "2.1.0"
  - "2.3.0"
services: redis

before_install:
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - echo "Host localhost" >> /home/travis/.ssh/config
  - echo "  StrictHostKeyChecking no" >> /home/travis/.ssh/config
  - chmod g-rw,o-rw /home/travis/.ssh/*

install:
  - bundle install --jobs=3 --retry=3 --deployment --full-index
